FROM tensorflow/tensorflow:2.9.1-gpu

# Create a working directory
RUN mkdir /app
WORKDIR /app

# Install deps
COPY requirements.txt.3.10 ./
RUN pip3 install -r requirements.txt.3.10
RUN pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html

CMD ["python3"]